// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: XHIMLogin.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - XhimloginRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface XhimloginRoot : GPBRootObject
@end

#pragma mark - XHImLoginRequest

typedef GPB_ENUM(XHImLoginRequest_FieldNumber) {
  XHImLoginRequest_FieldNumber_UserId = 1,
  XHImLoginRequest_FieldNumber_UserSign = 2,
};

/**
 * code=1003 登陆请求
 **/
GPB_FINAL @interface XHImLoginRequest : GPBMessage

/** 用户id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;

/** 用户签名 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *userSign;

@end

#pragma mark - XHImLoginResponse

typedef GPB_ENUM(XHImLoginResponse_FieldNumber) {
  XHImLoginResponse_FieldNumber_UserId = 1,
  XHImLoginResponse_FieldNumber_Status = 2,
};

/**
 * code=1004 登陆返回
 **/
GPB_FINAL @interface XHImLoginResponse : GPBMessage

/** 用户id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;

/** 返回结果 1=成功 2=失败 */
@property(nonatomic, readwrite) int32_t status;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
